[package]
name = "ip"
version = "0.1.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.7"
tokio = { version = "0.2.22", features = ["full"] }
pretty_env_logger = "0.4"
